### ISSUE TITLE
[BUG] Null fields in Metatype causes internal error

### ISSUE THREAD

**Issue by luisvaldez7741** [tylim88/Firelord#13]
Using latest version (2.1.8)

**1. What is the Meta Type?**
```
export type Timesheet = MetaTypeCreator<
  {
    user: DocumentReference<User>;
    submitted: boolean;
    submittedAt: Date | null;
    startDate: Date;
    endDate: Date;
  },
  `timesheets`,
  string,
  Company
>;
```
**2. What operations are you trying to run?**

Trying to run addDoc operation
```
addDoc(firestoreTimesheetType.collection(companyId), {
      endDate: Timestamp.fromDate(new Date(date.lastDay)),
      startDate: Timestamp.fromDate(new Date(date.firstDay)),
      submitted: false,
      submittedAt: null,
      user: firestoreUserType.doc(uid),
    });
```
**3. What do you expect?**

I expected it to submit the data even though the `submittedAt` field is `null`.

**5. What do you see?**

I could not send a the `submittedAt` as a `null` field. I tried making it optional, making it PossibleReadAsUndefined, but nothing seems to work.
After debugging I understood that if I set the `submittedAt` to a Date it works. Is there a way to insert null fields in the database with firelordjs? 
The error is the one below.
![image](https://user-images.githubusercontent.com/105426465/193598952-067a48a6-62c6-444f-a04d-45a169f08a6c.png)

Did I miss something in the docs?

**Comment by tylim88** [comment]
oh damn, please wait

**Comment by tylim88** [comment]
please try version 2.1.9

**Comment by luisvaldez7741** [comment]
Fixed. Well done! Thanks a lot! Congrats on the amazing project.

**Comment by tylim88** [comment]
thanks for using Firelord and reporting the bug 👍
