### ISSUE TITLE
[BUG] Argument of type 'CollectionReference<Example>' is not assignable to parameter of type 'CollectionReference<MetaType>'

### ISSUE THREAD

**Issue by came** [tylim88/Firelord#16]
1. Version?
2.1.9

2. What operations are you trying to run?
```
await addDoc(example.collection(), {
            a: 900,
            b: { c: false, d: [{ e: 'hi' }] },
            f: { g: serverTimestamp(), h: 3838 },
        })
```

3. What do you expect?
I wouldn't expect type errors ;)

4. What do you see?
```
Argument of type 'CollectionReference<Example>' is not assignable to parameter of type 'CollectionReference<MetaType>'.
  Property 'type' is missing in type 'CollectionReference<Example>' but required in type 'CollectionReference<MetaType>'.ts(2345)
refs.d.ts(36, 14): 'type' is declared here.
```

**Comment by tylim88** [comment]
what is your meta type?

**Comment by came** [comment]
mmmh ...I am little confused, what do you mean by my MetaType?
Like this:?

```
export type Example = MetaTypeCreator<
    {
        a: number
        b: { c: boolean; d: { e: string }[] }
        f: { g: ServerTimestamp; h: 1010 | 2929 | 3838 }
    }, // can go with even more crazy looking data type
    'SomeCollectionName', // collection ID type, must be string literal
    string // optional, document ID type, default string
> 
```

`export const example = getFirelord<Example>(db, 'SomeCollectionName') // this is your firelordRef`

**Comment by tylim88** [comment]
yes, MetaType is the one created by `MetaTypeCreator`

seem like this is the type from the example

working on the bug now

**Comment by came** [comment]
ok, Then I guessed right 😄  ...yes, I tried the example one
![refresh_testdata_ts_—_mycraftid](https://user-images.githubusercontent.com/149962/211399515-4953e242-4474-4381-bfa1-c4382dbb9e68.jpg)

**Comment by came** [comment]
I am using ts version 4.9.4. It's a private nextjs repo without anything special. The error is in an api function if that helps. Anything else I could check or specifically info that would be helpful to narrow the error down?

Here are some dependencies: 

"firebase": "^9.15.0",
 "firebase-admin": "^11.4.1",
 "firelord": "^2.1.9",
 "firelordjs": "^2.1.10",
"reactfire": "^4.2.2"

**Comment by tylim88** [comment]
the property `type` only exist in Web version

I think you accidentally mixed FirelordJS and Firelord

You use Firelordjs addDoc for Firelord Reference

**Comment by came** [comment]
🙈  ... I am sorry. Of course, that was the problem. Thank you so much 😄

**Comment by tylim88** [comment]
it is ok, I don't mind

just to confirm, is it ok now?

**Comment by came** [comment]
yes, all types just flow ...it's beautiful ❤️

**Comment by tylim88** [comment]
I will close this, if you have another issue or question, feel free to open issue again

or you can find me in the discord
