### ISSUE TITLE
[BUG] Can Firelord run on firebase functions?

### ISSUE THREAD

**Issue by came** [tylim88/Firelord#17]
1. Version?
"firebase-admin": "^11.5.0",
"firebase-functions": "^4.2.1",
"firelord": "^2.3.6",

3. What is the Meta Type?
not relevant
5. What operations are you trying to run?
not relevant
6. What do you expect?
I would like to use firelord in a firebase function
8. What do you see?
I receive an error when deploying the function code to firebase (see: 👇)
This import seems to be the problem: (https://github.com/tylim88/Firelord/blob/f4eb307ae0df0503dc5085566f8367aed05cd378/src/index.ts#L62)
Actually I have never used firebase/firestore never before.

- is it a possible to run firelord on firebase functions?
- Why do get this error? Do I need to install firebase/firestore in my firebase functions?

![Cursor_and_Logs_Explorer_–_Logging_–_mycraftid_–_Google_Cloud_console](https://user-images.githubusercontent.com/149962/224064583-5ae8feda-82ed-4f01-b608-ae5ed0caa72d.jpg)

**Comment by tylim88** [comment]
ah damn

**Comment by tylim88** [comment]
please use [2.3.7 ](https://github.com/tylim88/Firelord/releases/tag/2.3.7)

**Comment by came** [comment]
👍 ...deployment works. Thank you very much
