### ISSUE TITLE
[BUG] How do I allow auto generation of document Id

### ISSUE THREAD

**Issue by sushantdhiman** [tylim88/Firelord#18]
1. Version: `2.4.1`
2. What is the Meta Type?

```ts
<{ email: string; locked: string; }, 'sessions'>
```

3. What operations are you trying to run?

```ts
const ref = sessions.doc();
await createDoc(ref, { email: 'something', locked: false })
```

4. What do you expect?

I expected no error when trying to use `sessions.doc()`, as in vanilla `firebase-admin` it would have generated a document with auto generated id

5. What do you see?

```ts
src/routers/session.ts:14:32 - error TS2554: Expected 1 arguments, but got 0.

14     const reference = sessions.doc();
                                  ~~~~~

  node_modules/firelord/dist/types/doc.d.ts:9:59
    9     <D extends GetOddOrEvenSegments<T['docPath'], false>>(...documentIDs: D extends never ? D : IsValidDocIDLoop<D>): DocumentReference<T>;
                                                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Arguments for the rest parameter 'documentIDs' were not provided.

```

**Comment by tylim88** [comment]
![image](https://user-images.githubusercontent.com/5227509/228364007-b25af47e-4557-488f-af28-81275e71de08.png)
https://stackoverflow.com/questions/69859073/genrate-doc-id-in-firestore-v9-before-the-doc-is-created
the logic follow web V9 
![image](https://user-images.githubusercontent.com/5227509/228364151-f920ee4e-8c53-4301-89e2-5cd9748e0273.png)
https://stackoverflow.com/questions/69859073/genrate-doc-id-in-firestore-v9-before-the-doc-is-created

**Comment by sushantdhiman** [comment]
Thanks, I have added following helpers to my codebase.

```ts
import { FirelordRef, CollectionReference, DocumentSnapshot } from 'firelord';

type FirelordMetaTypeExtractor<T extends FirelordRef<any>> =
  T['collection'] extends (...args: any) => CollectionReference<infer P>
    ? P
    : never;

export type FirelordDocumentSnapshot<T extends FirelordRef<any>> =
  DocumentSnapshot<FirelordMetaTypeExtractor<T>>;

export type FirelordDocumentID<T extends FirelordRef<any>> =
  FirelordMetaTypeExtractor<T>['docID'];
```
