### ISSUE TITLE
[ENHANCEMENT] Provide type helper to extract DocumentSnapshot from collection

### ISSUE THREAD

**Issue by sushantdhiman** [tylim88/Firelord#19]
I have following code in my project :-

```ts

/*** db.ts ***/
type SessionMetaType = MetaTypeCreator<{ email: string; locked: string; }, 'sessions'>

export type SessionDocumentSnapshot = DocumentSnapshot<SessionMetaType>;
export const sessions = getFirelord<SessionMetaType>(firestore, 'sessions')


/*** logics.ts ***/
export function findValidSession(id: string) : SessionDocumentSnapshot {
   // some logic which returns document, also throws some error when certain conditions are met
}

```

To follow DRY and reducing code, `firelord` could provide some type helpers for following cases

1. Type helper to extract `DocumentSnapshot<SessionMetaType>` for any given "collection" kind. For example :-

```ts
   export const sessions = getFirelord<SessionMetaType>(firestore, 'sessions');
   export type SessionDocumentSnapshot = ExtractSnapshotType<typeof sessions>;
```

2. Although it is simple to do in my codebse, if possible, please provide type helper to extract documentId type from "collection" type

```ts
   export const sessions = getFirelord<SessionMetaType>(firestore, 'sessions', number);
   export type SessionDocumentId = ExtractDocumentIdType<typeof sessions>; // number
```

**Comment by tylim88** [comment]
as for documentSnapshot, you can use this

```ts
import { DocumentSnapshot } from 'firelord'

type SessionDocumentSnapshot = DocumentSnapshot<SessionMetaType>
```

see more [exported types](https://firelordjs.com/firelord/exports#type-definitions)

**Comment by sushantdhiman** [comment]
Thanks for this information, I was trying to find this information in [`Set`](https://firelordjs.com/highlights/set)
