### ISSUE TITLE
[QUESTION] Nested collection paths

### ISSUE THREAD

**Issue by hannojg** [tylim88/Firelord#21]
Hey, 

thank you for this library!

Maybe I missed something while reading the docs, but I have the following problem. Not all collections are at the root level of the firestorm database.

For example, I have this collection path:

```js
const userId = "someDynamicString";

firestore().collection(`users/${userId}/posts`)
```

I am confused how I use this format with firelord?

Should I just create one collection schema for user, where we have a property with posts, and then there is some magic to call that collection (I don't think that's how firelord works, no?)

otherwise, can you explain how to reference the collection then?

Maybe we can update the docs to make this clearer for first time users 😊

**Comment by hannojg** [comment]
I tried it like this:

```typescript
import { MetaTypeCreator } from 'firelord'
import { DBProfileRecording } from '../../../../common/api/profileRecordings'

export type DBProfileRecordingMetaType = MetaTypeCreator<
  DBProfileRecording,
  `users/${string}/recordings`
>
```

which does seem okay, however, when trying to use it I get a bunch of weird errors:

```typescript
   // ⚠️ Expected 3 arguments, but got 2.
    const recordingRef = getFirelord<DBProfileRecordingMetaType>(
      getFirestore(),
      `users/${context.auth.uid}/recordings`
    ).doc(data.recordingId)
    // ⚠️ Argument of type 'string' is not assignable to parameter of type 'CollectionReference<{ base: DBProfileRecording; read: { userId: string; createdAt: number; title: string; storagePath: string; sharedWith: "Error: undefined is not a valid Firestore type" | string[]; type: "video" | "drawing"; } | { ...; }; ... 9 more ...; ancestors: [...]; }>'.
```

**Comment by tylim88** [comment]
the details is in https://firelordjs.com/guides/metatype

it demonstrates how to build paths until grand children 

long thing short, Firelord assumes collection name is static (dynamic collection name does not make sense) and will always reuse it automatically

let me know if you need more clarification
